export const campaign = {
  nonprofitName: "New World Kids",
  campaignName: "The New World Kids Lowrider Bike Build",
  shortName: "Lowrider Bike Build",
  tagline: "A Seattle-local art bike build raising funds for New World Kids programs.",
  heroHeadline: "Transforming a One-of-a-Kind Bike Into a Collectible Work of Art",
  heroSubheadline: "New World Kids is bringing artists, supporters, and Seattle community together to turn a notable bike into a custom lowrider art piece that funds New World Kids programs.",
  affiliationNotice: "This campaign is not affiliated with, sponsored by, or endorsed by any professional sports league, team, or rights holder.",
  donationUrl: process.env.NEXT_PUBLIC_DONATION_URL || "#support-the-build",
  artistApplicationUrl: process.env.NEXT_PUBLIC_ARTIST_APPLICATION_URL || "#artist-application",
  sponsorInquiryUrl: process.env.NEXT_PUBLIC_SPONSOR_INQUIRY_URL || "#sponsor-inquiry",
  auctionUrl: process.env.NEXT_PUBLIC_AUCTION_URL || "#auction-coming-soon",
  totalGoalUsd: 50000,
  currentRaisedUsd: 0,
  auctionEnabled: false,
  raffleEnabled: false,
  bike360: { folder: "/assets/bike/360/", amountX: 36, indexZeroBase: 3, fallbackImage: "/assets/bike/story/current-bike.jpg" },
  model: { glbPath: "/assets/bike/model/bike.glb", usdzPath: "/assets/bike/model/bike.usdz" },
} as const;
